# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/test
CFG_INC=-Iinclude -I${HOME}/Projects 
CFG_LIB=/Users/dayton/Projects/oscpp/Debug//oscpp.dylib 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/test.o $(OUTDIR)/testDynamicLibrary.o \
	$(OUTDIR)/testSystemException.o $(OUTDIR)/testTrim.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/test.o $(OUTDIR)/testDynamicLibrary.o \
	$(OUTDIR)/testSystemException.o $(OUTDIR)/testTrim.o \
	/Users/dayton/Projects/oscpp/Debug//oscpp.dylib 

COMPILE=clang++ -c   -g -Werror -W -Waggregate-return -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wcomment -Wconversion -Werror-implicit-function-declaration -Wfloat-equal -Wformat -Wimplicit -Winline -Wmain -Wmissing-declarations -Wmissing-noreturn -Wmissing-prototypes -Wmultichar -Wnested-externs -Wpacked -Wparentheses -Wpointer-arith -Wredundant-decls -Wreorder -Wreturn-type -Wshadow -Wsign-compare -Wstrict-prototypes -Wswitch -Wunreachable-code -Wunused -Wuninitialized -Wunknown-pragmas -Wwrite-strings -std=c++11 -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=clang++  -g -Werror -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : test/%.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) deps $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Build dependencies
deps:
	@(cd .;$(MAKE) -f oscpp.mak CFG=$(CFG))
	@(cd test/mockstrerror/;$(MAKE) -f mockstrerror.mak CFG=$(CFG))

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
	@(cd .;$(MAKE) -f oscpp.mak cleanall CFG=$(CFG))
	@(cd test/mockstrerror/;$(MAKE) -f mockstrerror.mak cleanall CFG=$(CFG))
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/test
CFG_INC=-Iinclude -I${HOME}/Projects 
CFG_LIB=/Users/dayton/Projects/oscpp/Release//oscpp.dylib 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/test.o $(OUTDIR)/testDynamicLibrary.o \
	$(OUTDIR)/testSystemException.o $(OUTDIR)/testTrim.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/test.o $(OUTDIR)/testDynamicLibrary.o \
	$(OUTDIR)/testSystemException.o $(OUTDIR)/testTrim.o \
	/Users/dayton/Projects/oscpp/Release//oscpp.dylib 

COMPILE=clang++ -c   -std=c++11 -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=clang++  -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : test/%.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) deps $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Build dependencies
deps:
	@(cd .;$(MAKE) -f oscpp.mak CFG=$(CFG))
	@(cd test/mockstrerror/;$(MAKE) -f mockstrerror.mak CFG=$(CFG))

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
	@(cd .;$(MAKE) -f oscpp.mak cleanall CFG=$(CFG))
	@(cd test/mockstrerror/;$(MAKE) -f mockstrerror.mak cleanall CFG=$(CFG))
endif
